name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change Directory to Flask App
        run: |
          cd /var/www/html
          ls -al

      - name: Verify Git Repository
        run: |
          git status
          git remote -v
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug - Check Virtual Environment
        run: |
          ls -al /var/www/html/venv
        working-directory: /var/www/html

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DONGI }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html 
            source venv/bin/activate
            git pull origin main 
            pip install -r requirements.txt
            /var/www/html/venv/bin/gunicorn -w 4 -b 0.0.0.0:8000 app:app
        timeout-minutes: 1
        continue-on-error: true

      - name: Activate Virtual Environment
        run: |
          if [ -f /var/www/html/venv/bin/activate ]; then
            source /var/www/html/venv/bin/activate
          else
             echo "Virtual environment not found."
             exit 1
          fi
        working-directory: /var/www/html
        continue-on-error: true
