name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change Directory Permissions
        run: sudo chmod -R 777 /var/www/html

      - name: Change Directory to Flask App
        run: |
          cd /var/www/html
          ls -al

      - name: Verify Git Repository
        run: |
          git status
          git remote -v
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create and Activate Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
        continue-on-error: true

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        continue-on-error: true

      - name: Check processes on port 8000 (before)
        run: sudo lsof -i :8000

      # - name: Kill existing Gunicorn processes
      #   run: sudo pkill gunicorn || true

      - name: Check processes on port 8000 (after)
        run: sudo lsof -i :8000

      - name: Add a delay
        run: sleep 5

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DONGI }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html 
            source venv/bin/activate
            git pull origin main 
            pip install -r requirements.txt
            /var/www/html/venv/bin/gunicorn -w 4 -b 0.0.0.0:8000 app:app
        timeout-minutes: 15
        continue-on-error: true

      - name: Check Service Status
        run: |
          sudo systemctl status todoapp.service
        continue-on-error: true
