name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    # needs: test
    # runs-on: ubuntu-latest

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    #   - name: Set up Python
    #     uses: actions/setup-python@v2
    #     with:
    #       python-version: 3.8

    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.txt
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH Key
        run: |
          echo "SSH_PRIVATE_KEY_DONGI: ${{ secrets.SSH_PRIVATE_KEY_DONGI }}"
          echo "HOST: ${{ secrets.HOST }}"
          echo "SSH_USER: ${{ secrets.SSH_USER }}"
          echo "SSH_PORT: ${{ secrets.SSH_PORT }}"
        env:
          SSH_PRIVATE_KEY_DONGI: ${{ secrets.SSH_PRIVATE_KEY_DONGI }}
          HOST: ${{ secrets.HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DONGI }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/ToDoApp
            git pull origin main  
            source venv/bin/activate
            pip install -r requirements.txt
            /root/ToDoApp/venv/bin/gunicorn -w 4 -b 0.0.0.0:5000 app:app
