name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Deploy to Digital Ocean
        run: |
          scp -r ToDoApp/* root@64.225.64.147:/root/ToDoApp/
          ssh root@64.225.64.147 'cd /root/ToDoApp && gunicorn -w 4 -b 0.0.0.0:5000 app:app'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
