name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DONGI }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html 
            source venv/bin/activate
            git pull origin main 
            pip install -r requirements.txt  
            systemctl restart todoapp.service
            sudo systemctl status todoapp.service

        timeout-minutes: 15
        continue-on-error: true
